rails/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :pay_accounts
  get 'root/index'
  root to: 'root#index'

  resources :expenses
  resources :stores
  resources :receipt_details
  resources :receipts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  post 'receipts/xml_upload', to: 'receipts#xml_upload'
  post 'receipts/csv_upload', to: 'receipts#csv_upload'

  post 'receipt_details/xml_upload', to: 'receipt_details#xml_upload'
  post 'receipt_details/csv_upload', to: 'receipt_details#csv_upload'
end

rails/app/models/receipt.rb
require 'csv'

class Receipt < ApplicationRecord
  belongs_to :store
  belongs_to :pay_account, optional: true
  has_many :receipt_details, dependent: :delete_all
  accepts_nested_attributes_for :receipt_details
  attr_accessor :store_name

  scope :search, lambda { |search_word| where("date LIKE ?", "%#{search_word}%") }

  class CsvFormat 
    def initialize
      create_xxxx_headar
    end

    # [テーブル名]_headerでヘッダー名を返す
    # 例：
    # reciept_header
    # => ["id", "name"]
    # receipt_HEADER
    # => ["receipt/id", "receipt/name"]
    def create_xxxx_headar
      arr = HEADER.group_by {|e| e.split("/")[0]}
      arr.each do |table_name, column_name|
        CsvFormat.class_eval do
          define_method "#{table_name}_header" do
            column_name.map { |e| e.split("/")[1] }
          end
          define_method "#{table_name}_HEADER" do
            column_name.map{|e| e}
          end
        end
      end
    end

    # receipt_attributes(csv)で、テーブルに存在するキーのみのhashを作る
    # 例：
    # reciept_attributes({"receipt/id" => "hoge", "fuga/name" => "fuga"})
    # => {id: "hoge"}
    def receipt_attributes(fg)
      h = fg.to_hash.select {|e| receipt_HEADER.include?(e)}
      result = {}

      h.each do |k, v|
        result.merge({k.split("/")[1] => v})
      end

      result
    end

    HEADER = 
      [
        "receipt/id",
        "receipt/date",
        "store/name",
        "store/tel",
        "pay_account/name",
        "receipt_detail/price",
        "receipt_detail/expense",
        "receipt_detail/name",
      ].freeze
  end

  def self.to_csv
    bom = %w(EF BB BF).map { |e| e.hex.chr }.join
    CSV.generate(bom) do |csv|

      formatter = CsvFormat.new

      receipt_header = formatter.receipt_header
      store_header = formatter.store_header
      pay_account_header = formatter.pay_account_header
      receipt_detail_header = formatter.receipt_detail_header

      # column_namesはカラム名を配列で返す
      # 例: ["id", "name", "price", "released_on", ...]
      h = CsvFormat::HEADER

      csv << h

      all.preload(:store, :pay_account, :receipt_details).each do |e|
        # attributes はカラム名と値のハッシュを返す
        # 例: {"id"=>1, "name"=>"レコーダー", "price"=>3000, ... }
        # valudes_at はハッシュから引数で指定したキーに対応する値を取り出し、配列にして返す
        # 下の行は最終的に column_namesで指定したvalue値の配列を返す
        # 「*」を付与することによって配列を出力した状態で返す
        v1 =  e.attributes.values_at(*receipt_header)
        v2 = e.store ? e.store.attributes.values_at(*store_header) : ""
        v3 = e.pay_account ? e.pay_account.attributes.values_at(*pay_account_header) : ""
        if e.receipt_details
          v4 = e.receipt_details.sum(:price)

          expense_ids = e.receipt_details.distinct.pluck(:expense_id)
          expense_names = Expense.where(id: expense_ids).map{|e| e.name}
          v5 = expense_names.join(", ")
          v6 = e.receipt_details.map{|e| e.name}.join(", ")
        else
          v4 = ""
          v5 = ""
          v6 = ""
        end
        
        csv << [*v1, *v2, *v3, v4, v5, v6]
      end
    end
  end

  def self.from_csv(file)
    stores = Store.all.map{|e| [e[:id], e[:name]]}
    pay_accounts = PayAccount.all.map{|e| [e[:id], e[:name]]}
    expenses = Expense.all.map{|e| [e[:id], e[:name]]}

    formatter = CsvFormat.new

    count = 0
    logger.info "-----------CSVの読み込み_開始-----------"
    CSV.foreach(file.path, headers: true, encoding: 'UTF-8', undef: :replace, replace: "*") do |fg|
      #TODO BOM付きファイルについて対応するか検討が必要
      #      CSV.foreach(file.path, headers: true, encoding: 'BOM|UTF-8:Shift_JIS', undef: :replace, replace: "*") do |fg|

      fg.map{|e| e.last&.encode!("utf-8")}

      record = preload(:store, :pay_account).find_or_initialize_by(id: fg["receipt/id"])

      update_attributes = formatter.receipt_attributes(fg)

      store_id = nil
      pay_account_id = nil

      # store_idをstore/nameから引き当てる
      if fg["store/name"]
        if fg["store/name"] != record.store&.name
          store_id = stores.find(->{[nil, nil]}) {|id, name| fg["store/name"] == name}[0]

          update_attributes.merge!({"store_id" => store_id})
        end
      end

      # pay_account_idをpay_account/nameから引き当てる
      if fg["pay_account/name"] 
        if fg["pay_account/name"] != record.pay_account&.name
          pay_account_id = pay_accounts.find(->{[nil, nil]}){|id, name| 
            fg["pay_account/name"] == name
          }[0]
    
          update_attributes.merge!({"pay_account_id" => pay_account_id})
        end
      end

=begin
      # expense_idをreceipt_detail/expense(name)から引き当てる
      if fg["receipt_detail/expense"] && fg["receipt_detail/expense"]
        expense_id = expenses.find(->{[nil, nil]}){|id, name| fg["receipt_detail/expense"] == name}[0]
        update_attributes.merge!({"receipt_details" => {"expense_id" => expense_id})
      end
=end

      # 違いがあるレコードのみ更新する
      new_attr      = update_attributes.slice(*updatable_attributes)
      original_attr = record.attributes.slice(*(new_attr.keys))

      saved_count = 0

      if original_attr != new_attr
        logger.info "★現在：#{original_attr}"
        logger.info "★更新：#{new_attr}"

        record.attributes = new_attr
        record.save
        saved_count = 1
      end

      # 関連レコードも更新する

      expense_id = nil

      if record.receipt_details
        # receipt_detail/expense_idをreceipt_detail/expenseから引き当てる
        if fg["receipt_detail/expense"]
          input_expense_arr = fg["receipt_detail/expense"].split(",")

          # receipt_detail/expense_idが1の場合、かつレコードの値と一致しない場合のみ更新
          if input_expense_arr.length == 1 && record.receipt_details.map{|e| e.expense&.name}.uniq.sort != input_expense_arr.uniq.sort
            expense_id = expenses.find(->{[nil, nil]}){|id, name| input_expense_arr[0] == name }[0]
          end

          record.receipt_details.each do |e|
            if expense_id && e.expense_id != expense_id
              e.expense_id = expense_id
              e.save
              saved_count = 1
            end
          end
        end
      end

      count += saved_count
    end
    logger.info "-----------CSVの読み込み_終了-----------"
    count
  end

  def self.from_xml(file)

    count = 0
    doc = REXML::Document.new(file.read)

    doc.elements.each('receipt_data/receipt_list/receipt') do |receipt|

      next unless receipt

      # 参考情報としてreceipt_idをmemoに登録しておく
      memo = "receipt_id: " + receipt.elements['receipt_id']&.text

      store_name = receipt.elements['store']&.text
      store_tel = receipt.elements['tel']&.text
      date = receipt.elements['date']&.text

      date = nil unless date_valid?(date)

      # --------------------------------------------------------------------------------
      # 電文解析
      # --------------------------------------------------------------------------------

      # 店舗
      # nameとtelで検索してすでに存在していればその値を取得
      store = Store.find_or_initialize_by(name: store_name, tel: store_tel)

      # 明細
      receipt_details = []

      receipt.elements.each('item_list/item') do |receipt_detail|
        receipt_detail_price = receipt_detail.elements['price']&.text&.to_i
        receipt_detail_name = receipt_detail.elements['name']&.text
        receipt_details << {price: receipt_detail_price, name: receipt_detail_name}
      end
      
      # バリデーション
      next if validate(date, store_tel, store_name, receipt_details)
      
      # 登録
      self.transaction do
        new_receipt = Receipt.create(date: date, store: store, memo: memo)
        new_receipt.receipt_details.create(receipt_details)
        count += 1
      end
    end

    count
  end

  private

  def self.date_valid?(str)
    !! Date.parse(str) rescue false
  end

  # --------------------------------------------------------------------------------
  # バリデーション
  # ・日付、店舗の電話番号、合計金額が一致してるレコードを取得。
  # ・一致してたレコードのうち、明細も全て同じの場合は登録済みとしてスキップ。
  # ・[TODO]明細が違う場合は、登録は実行しておいて警告を出す。
  # --------------------------------------------------------------------------------
  def self.validate(date, store_tel, store_name, receipt_details)

    hits = Receipt.joins(:store, :receipt_details).where(date: date, stores: {tel: store_tel, name: store_name})
    isExistReceipt = false

    if hits.present?
      # 日付、店舗の電話番号が一致しているレコードある場合
      total = receipt_details.sum { |h| h[:price]}

      hits.each do |hit|
        isMatchPrice = false
        isMatchDetail = false
        # 金額を確認
        if hit.receipt_details.sum(:price) == total
          isMatchPrice = true
        end

        # 金額が合致している場合は明細を確認
        if isMatchPrice
          isMatchDetail = true
          hit.receipt_details.each_with_index do |hit_receipt_detail, i|
            if receipt_details[i][:name] != hit_receipt_detail.name
              isMatchDetail = false
              break
            end
          end
        end

        # 金額と明細が一致したレコードは無視する
        if isMatchPrice && isMatchDetail
          isExistReceipt = true
          break
        end
      end
    end

    isExistReceipt
  end

  def self.updatable_attributes
#    ["date", "store_id", "pay_account_id"]
    ["date", "pay_account_id"]
  end

end

rails/app/controllers/receipts_controller.rb
require 'rexml/document'

class ReceiptsController < ApplicationController
  before_action :set_receipt, only: [:show, :edit, :update, :destroy]

  # GET /receipts
  # GET /receipts.json
  def index
     if search_params[:search]
       @receipts = Receipt.search(search_params[:search]).preload(:store, :receipt_details, :pay_account, receipt_details: :expense).order(date: "DESC")
     elsif sort_params[:sort] == "expense"
       @receipts = Receipt.eager_load(:store, :receipt_details, :pay_account, receipt_details: :expense).order("receipt_details.expense_id").all  
     else
       @receipts = Receipt.eager_load(:store, :receipt_details, :pay_account, receipt_details: :expense).order(date: "DESC").all  
     end

     respond_to do |format|
       format.html
       format.json
       format.csv { send_data @receipts.to_csv }
     end
  end

  # POST /csv_upload
  def csv_upload
    msg = ""
    saved_record_num = 0

    file = csv_params[:csv_upload]

    saved_record_num = Receipt.from_csv(file)

    msg += "CSV import succeed!#{saved_record_num}件登録しました。"
    flash[:notice] = msg
    redirect_to action: "index"
  end

  # POST /xml_upload
  def xml_upload
    msg = ""
    file = xml_params[:xml_upload]

    saved_record_num = Receipt.from_xml(file)

    msg += "XML import succeed!#{saved_record_num}件登録しました。"

    flash[:notice] = msg
    redirect_to action: "index"
  end

  # GET /receipts/1
  # GET /receipts/1.json
  def show
  end

  # GET /receipts/new
  def new
    @receipt = Receipt.new
    2.times { @receipt.receipt_details.build }
  end

  # GET /receipts/1/edit
  def edit
  end

  # POST /receipts
  # POST /receipts.json
  def create
    date = Date.new(receipt_params["date(1i)"].to_i, receipt_params["date(2i)"].to_i, receipt_params["date(3i)"].to_i)

    @receipt = Receipt.new(date: date, store_id: receipt_params[:store_id], pay_account_id: receipt_params[:pay_account_id])
    receipt_params[:receipt_details_attributes].to_h.values.each do |receipt_detail|
      # id, store_id, priceいずれも入力値が空の場合は除外
      next if receipt_detail.values.all?{|e| e.blank?}

      @receipt.receipt_details.build(receipt_detail)
    end

    respond_to do |format|
      if @receipt.save
        format.html { redirect_to @receipt, notice: 'Receipt was successfully created.' }
        format.json { render :show, status: :created, location: @receipt }
      else
        format.html { render :new }
        format.json { render json: @receipt.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /receipts/1
  # PATCH/PUT /receipts/1.json
  def update
    respond_to do |format|
      if @receipt.update(receipt_params)
        format.html { redirect_to receipts_url, notice: 'Receipt was successfully updated.' }
        format.json { render :show, status: :ok, location: @receipt }
      else
        format.html { render :edit }
        format.json { render json: @receipt.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /receipts/1
  # DELETE /receipts/1.json
  def destroy
    @receipt.destroy
    respond_to do |format|
      format.html { redirect_to receipts_url, notice: 'Receipt was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_receipt
      @receipt = Receipt.preload(:store, :pay_account, :receipt_details).find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def receipt_params
      params.require(:receipt).permit(
        :date, 
        :store_id, 
        :pay_account_id, 
        receipt_details_attributes: [:id, :name, :price, :expense_id])
    end

    def search_params
      params.permit(:search)
    end

    def sort_params
      params.permit(:sort)
    end

    def xml_params
      params.permit(:xml_upload)
    end

    def csv_params
      params.permit(:csv_upload)
    end
end

rails/app/helpers/receipts_helper.rb
module ReceiptsHelper
end

rails/app/views/receipts/_form.html.erb
<%= form_for(receipt) do |f| %>
  <% if receipt.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(receipt.errors.count, "error") %> prohibited this receipt from being saved:</h2>

      <ul>
      <% receipt.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <dl class="field">
    <dt><%= f.label :date %>
    <dd><%= f.date_select :date %>
  </dl>

  <dl class="field">
    <dt><%= f.label :store_id %>
    <dd><%= f.select :store_id , store_list %>
  </dl>

  <dl class="field">
    <dt><%= f.label :pay_account_id %>
    <dd><%= f.select :pay_account_id , pay_account_list %>
  </dl>

  <dl class="field">
    <dt><%= f.label :receipt_details %>
    <dd>
      <table>
        <thead>
          <tr>
            <td colspan="2">
            <td><%= select :selectbox, :for_expense_all_change, expense_list %>
            <td>
              <%= link_to(
              'All Change!', 
              'javascript:void(0);',
              onclick: 'expense_all_change();',
              style: 'font-weight:bold;'
              ) %>
            </td>
          </tr>
          <tr>
            <th>Name
            <th>Price
            <th>Expense
          </tr>
        </thead>
        <tbody>
          <%= f.fields_for :receipt_details do |f_receipt_detail| %>
            <tr>
              <%= f_receipt_detail.hidden_field :id %>
<!--              <th><%= f_receipt_detail.label :name %>-->
              <td><%= f_receipt_detail.text_field :name %>
<!--              <th><%= f_receipt_detail.label :price %>-->
              <td><%= f_receipt_detail.number_field :price %>
<!--              <th><%= f_receipt_detail.label :expense_id %>-->
              <td><%= f_receipt_detail.select :expense_id , expense_list %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </dd>
  </dl>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

rails/app/views/receipts/edit.html.erb
<h1>Editing Receipt</h1>

<%= render 'form', receipt: @receipt %>

<%= link_to 'Show', @receipt %> |
<%= link_to 'Back', receipts_path %>

rails/app/views/receipts/index.html.erb
<p id="notice"><%= notice.html_safe if notice %></p>

<h1>All receipts</h1>

<%= form_tag receipts_path, :method => 'get' do %>
  <p>
    <%= text_field_tag :search, params[:search], placeholder: 'ex. 2018-08' %>
    <%= submit_tag "Search", name: nil %>
  </p>
<% end %>

<%= form_tag receipts_xml_upload_path, id: 'f_xml_upload', multipart: true do %>
  <p>
    <%= file_field_tag :xml_upload,
     onchange: "file_upload($('#f_xml_upload'), $(this));", 
     style: "display:none;" %>
  </p>
<% end %>
<%= form_tag receipts_csv_upload_path, id: 'f_csv_upload', multipart: true do %>
  <p>
    <%= file_field_tag :csv_upload,
     onchange: "file_upload($('#f_csv_upload'), $(this));", 
     style: "display:none;" %>
  </p>
<% end %>

<%= link_to 'New Receipt', new_receipt_path %>
<%= link_to "CSV download", receipts_path(format: "csv") %>
<%= link_to(
'XML upload',
'javascript:void(0);',
onclick: 'document.getElementById("xml_upload").click();',
) %>
<%= link_to(
'CSV upload',
'javascript:void(0);',
onclick: 'document.getElementById("csv_upload").click();',
) %>

<h1>Receipts</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Date</th>
      <th>Store</th>
      <th>Pay</th>
      <th>Detail
        <span style="float: right">(<%= link_to 'Expense Sort', receipts_path(sort: "expense") %>)</span>
      </th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @receipts.each do |receipt| %>
      <tr>
        <td><%= receipt.id %></td>
        <td><%= receipt.date %></td>
        <td><%= receipt.store.name %></td>
        <td>
          <% if receipt.pay_account.present? %>
            <%=receipt.pay_account.name %>
          <% end %>
        </td>
        <td>
          <table>
            <% receipt.receipt_details.each do |receipt_detail| %>
              <tr>
                <td width="300px;"><%=receipt_detail.name %>
                <td width="50px;">￥<%=receipt_detail.price %>
                <td width="50px;"><%=receipt_detail.expense&.name %>
              </tr>
            <% end %>
          </table>
        </td>
        <td>
          <%= link_to 'Show', receipt, class: "btn btn-outline-primary" %><br/>  
          <%= link_to 'Edit', edit_receipt_path(receipt), class: "btn btn-outline-success" %><br/>
          <%= link_to 'DeL', receipt, method: :delete, 
          data: {confirm: 'Are you sure?'}, class: "btn btn-outline-danger" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

rails/app/views/receipts/new.html.erb
<h1>New Receipt</h1>

<%= render 'form', receipt: @receipt %>

<%= link_to 'Back', receipts_path %>

rails/app/views/receipts/show.html.erb
<p id="notice"><%= notice %></p>

<dl>
  <dt><strong>Date:</strong>
  <dd><%= @receipt.date %>
</dl>
<dl>
  <dt><strong>Store:</strong>
  <dd><%= @receipt.store.name %>
</dl>
<dl>
  <dt><strong>Pay:</strong>
  <dd>
    <% if @receipt.pay_account.present? %>
      <%= @receipt.pay_account.name %>
    <% else %>
      <br/>
    <% end %>
</dl>
<dl>
  <dt><strong>Receipt Detail:</strong>
  <dd>
    <table>
      <thead>
        <tr>
          <th>Name
          <th>Price
          <th>Expense
        </tr>
      </thead>
      <% @receipt.receipt_details.each do |receipt_detail| %>
      <tbody>
        <tr>
          <td><%=receipt_detail.name %>
          <td>￥<%=receipt_detail.price %>
          <td>
            <% if receipt_detail.expense.present? %>
              <%=receipt_detail.expense.name %>
            <% end %>
        </tr>
      </tbody>
    <% end %>
    </table>
  </dd>
</dl>


<%= link_to 'Edit', edit_receipt_path(@receipt) %> |
<%= link_to 'Back', receipts_path %>