rails/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :pay_accounts
  get 'root/index'
  root to: 'root#index'

  resources :expenses
  resources :stores
  resources :receipt_details
  resources :receipts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  post 'receipts/xml_upload', to: 'receipts#xml_upload'
  post 'receipts/csv_upload', to: 'receipts#csv_upload'

  post 'receipt_details/xml_upload', to: 'receipt_details#xml_upload'
  post 'receipt_details/csv_upload', to: 'receipt_details#csv_upload'
end

rails/app/models/pay_account.rb
class PayAccount < ApplicationRecord
  has_many :receipts
end

rails/app/controllers/pay_accounts_controller.rb
class PayAccountsController < ApplicationController
  before_action :set_pay_account, only: [:show, :edit, :update, :destroy]

  # GET /pay_accounts
  # GET /pay_accounts.json
  def index
    @pay_accounts = PayAccount.all
  end

  # GET /pay_accounts/1
  # GET /pay_accounts/1.json
  def show
  end

  # GET /pay_accounts/new
  def new
    @pay_account = PayAccount.new
  end

  # GET /pay_accounts/1/edit
  def edit
  end

  # POST /pay_accounts
  # POST /pay_accounts.json
  def create
    @pay_account = PayAccount.new(pay_account_params)

    respond_to do |format|
      if @pay_account.save
        format.html { redirect_to @pay_account, notice: 'Pay account was successfully created.' }
        format.json { render :show, status: :created, location: @pay_account }
      else
        format.html { render :new }
        format.json { render json: @pay_account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pay_accounts/1
  # PATCH/PUT /pay_accounts/1.json
  def update
    respond_to do |format|
      if @pay_account.update(pay_account_params)
        format.html { redirect_to @pay_account, notice: 'Pay account was successfully updated.' }
        format.json { render :show, status: :ok, location: @pay_account }
      else
        format.html { render :edit }
        format.json { render json: @pay_account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pay_accounts/1
  # DELETE /pay_accounts/1.json
  def destroy
    @pay_account.destroy
    respond_to do |format|
      format.html { redirect_to pay_accounts_url, notice: 'Pay account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pay_account
      @pay_account = PayAccount.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pay_account_params
      params.require(:pay_account).permit(:name)
    end
end

rails/app/helpers/pay_accounts_helper.rb
module PayAccountsHelper
end

rails/app/views/pay_accounts/_form.html.erb
<%= form_for(pay_account) do |f| %>
  <% if pay_account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pay_account.errors.count, "error") %> prohibited this pay_account from being saved:</h2>

      <ul>
      <% pay_account.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

rails/app/views/pay_accounts/edit.html.erb
<h1>Editing Pay Account</h1>

<%= render 'form', pay_account: @pay_account %>

<%= link_to 'Show', @pay_account %> |
<%= link_to 'Back', pay_accounts_path %>

rails/app/views/pay_accounts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pay Accounts</h1>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pay_accounts.each do |pay_account| %>
      <tr>
        <td><%= pay_account.id %></td>
        <td><%= pay_account.name %></td>
        <td><%= link_to 'Show', pay_account %></td>
        <td><%= link_to 'Edit', edit_pay_account_path(pay_account) %></td>
        <td><%= link_to 'Destroy', pay_account, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pay Account', new_pay_account_path %>

rails/app/views/pay_accounts/new.html.erb
<h1>New Pay Account</h1>

<%= render 'form', pay_account: @pay_account %>

<%= link_to 'Back', pay_accounts_path %>

rails/app/views/pay_accounts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @pay_account.name %>
</p>

<%= link_to 'Edit', edit_pay_account_path(@pay_account) %> |
<%= link_to 'Back', pay_accounts_path %>