rails/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :pay_accounts
  get 'root/index'
  root to: 'root#index'

  resources :expenses
  resources :stores
  resources :receipt_details
  resources :receipts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  post 'receipts/xml_upload', to: 'receipts#xml_upload'
  post 'receipts/csv_upload', to: 'receipts#csv_upload'

  post 'receipt_details/xml_upload', to: 'receipt_details#xml_upload'
  post 'receipt_details/csv_upload', to: 'receipt_details#csv_upload'
end

rails/app/models/receipt_detail.rb
class ReceiptDetail < ApplicationRecord
  belongs_to :receipt
  belongs_to :expense, optional: true

  def self.to_csv
    CSV.generate do |csv|
      # column_namesはカラム名を配列で返す
      # 例: ["id", "name", "price", "released_on", ...]
      csv << column_names
      all.each do |column|
        # attributes はカラム名と値のハッシュを返す
        # 例: {"id"=>1, "name"=>"レコーダー", "price"=>3000, ... }
        # valudes_at はハッシュから引数で指定したキーに対応する値を取り出し、配列にして返す
        # 下の行は最終的に column_namesで指定したvalue値の配列を返す
        csv << column.attributes.values_at(*column_names)
      end
    end
  end

  def self.from_csv(file)
    count = 0
    CSV.foreach(file.path, headers: true) do |fg|
      record = self.find_or_initialize_by(id: fg["id"])
      record.attributes = fg.to_hash.slice(*updatable_attributes)

      record.save
      count += 1
    end
    count
  end

  def self.updatable_attributes
    ["expense_id", "price", "name"]
  end
end

rails/app/controllers/receipt_details_controller.rb
class ReceiptDetailsController < ApplicationController
  before_action :set_receipt_detail, only: [:show, :edit, :update, :destroy]

  # GET /receipt_details
  # GET /receipt_details.json
  def index
    @receipt_details = ReceiptDetail.includes(:expense, receipt: [:store]).all
    @receipt_details.each do |e|
      e.expense = Expense.new unless e.expense
    end

    respond_to do |format|
      format.html
      format.json
      format.csv { send_data @receipt_details.to_csv }
    end
  end

  # POST /csv_upload
  def csv_upload
    msg = ""
    saved_record_num = 0

    file = csv_params[:csv_upload]

    saved_record_num = ReceiptDetail.from_csv(file)

    msg += "CSV import succeed!#{saved_record_num}件登録しました。"
    flash[:notice] = msg
    redirect_to action: "index"
  end

  # GET /receipt_details/1
  # GET /receipt_details/1.json
  def show
  end

  # GET /receipt_details/new
  def new
    @receipt_detail = ReceiptDetail.new
  end

  # GET /receipt_details/1/edit
  def edit
  end

  # POST /receipt_details
  # POST /receipt_details.json
  def create
    @receipt_detail = ReceiptDetail.new(receipt_detail_params)

    respond_to do |format|
      if @receipt_detail.save
        format.html { redirect_to @receipt_detail, notice: 'Receipt detail was successfully created.' }
        format.json { render :show, status: :created, location: @receipt_detail }
      else
        format.html { render :new }
        format.json { render json: @receipt_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /receipt_details/1
  # PATCH/PUT /receipt_details/1.json
  def update
    respond_to do |format|
      if @receipt_detail.update(receipt_detail_params)
        format.html { redirect_to @receipt_detail, notice: 'Receipt detail was successfully updated.' }
        format.json { render :show, status: :ok, location: @receipt_detail }
      else
        format.html { render :edit }
        format.json { render json: @receipt_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /receipt_details/1
  # DELETE /receipt_details/1.json
  def destroy
    @receipt_detail.destroy
    respond_to do |format|
      format.html { redirect_to receipt_details_url, notice: 'Receipt detail was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_receipt_detail
      @receipt_detail = ReceiptDetail.find(params[:id])
      @receipt_detail.expense = Expense.new unless @receipt_detail.expense
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def receipt_detail_params
      params.require(:receipt_detail).permit(:expense_id, :price, :name, :receipt_id)
    end

    def csv_params
      params.permit(:csv_upload)
    end
end

rails/app/helpers/receipt_details_helper.rb
module ReceiptDetailsHelper
end

rails/app/views/receipt_details/_form.html.erb
<%= form_for(receipt_detail) do |f| %>
  <% if receipt_detail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(receipt_detail.errors.count, "error") %> prohibited this receipt_detail from being saved:</h2>

      <ul>
      <% receipt_detail.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :expense_id %>
    <%= f.number_field :expense_id %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.number_field :price %>
  </div>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

<!-- receipt -->
  <div class="field">
    <%= f.label :receipt_id %>
    <%= f.number_field :receipt_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

rails/app/views/receipt_details/edit.html.erb
<h1>Editing Receipt Detail</h1>

<%= render 'form', receipt_detail: @receipt_detail %>

<%= link_to 'Show', @receipt_detail %> |
<%= link_to 'Back', receipt_details_path %>

rails/app/views/receipt_details/index.html.erb
<p id="notice"><%= notice %></p>

<%= form_tag receipt_details_csv_upload_path, id: 'f_csv_upload', multipart: true do %>
  <p>
    <%= file_field_tag :csv_upload,
     onchange: "file_upload($('#f_csv_upload'), $(this));", 
     style: "display:none;" %>
  </p>
<% end %>

<%= link_to "CSV download", receipt_details_path(format: "csv") %>
<%= link_to(
'CSV upload',
'javascript:void(0);',
onclick: 'document.getElementById("csv_upload").click();',
) %>

<h1>Receipt Details</h1>

<table>
  <thead>
    <tr>
      <th>Receipt</th>
      <th>Expense</th>
      <th>Price</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @receipt_details.each do |receipt_detail| %>
      <tr>
        <td><%= receipt_detail.receipt.date %> <%= receipt_detail.receipt.store.name %></td>
        <td><%= receipt_detail.expense.name %></td>
        <td><%= receipt_detail.price %></td>
        <td><%= receipt_detail.name %></td>
        <td><%= link_to 'Show', receipt_detail %></td>
        <td><%= link_to 'Edit', edit_receipt_detail_path(receipt_detail) %></td>
        <td><%= link_to 'Destroy', receipt_detail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Receipt Detail', new_receipt_detail_path %>

rails/app/views/receipt_details/new.html.erb
<h1>New Receipt Detail</h1>

<%= render 'form', receipt_detail: @receipt_detail %>

<%= link_to 'Back', receipt_details_path %>

rails/app/views/receipt_details/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Expense:</strong>
  <%= @receipt_detail.expense_id %>
</p>

<p>
  <strong>Price:</strong>
  <%= @receipt_detail.price %>
</p>

<p>
  <strong>Name:</strong>
  <%= @receipt_detail.name %>
</p>

<%= link_to 'Edit', edit_receipt_detail_path(@receipt_detail) %> |
<%= link_to 'Back', receipt_details_path %>